In [53]:
import os
import sys

if "google.colab" in sys.modules:
    # Running in Colab

    !git clone https://github.com/pthengtr/kcw-analytics.git
    !cd /content/kcw-analytics && git pull origin main

    from google.colab import drive
    drive.mount("/content/drive")

    BASE_FOLDER = "/content/drive/Shareddrives"
    BASE_FOLDER_GIT = "/content"
else:
    # Running in local Jupyter
    BASE_FOLDER = r"G:\Shared drives"
    BASE_FOLDER_GIT = r"C:\Users\Windows 11\Notebook"

print("Using folder:", BASE_FOLDER)

fatal: destination path 'kcw-analytics' already exists and is not an empty directory.
From https://github.com/pthengtr/kcw-analytics
 * branch            main       -> FETCH_HEAD
Already up to date.
Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
Using folder: /content/drive/Shareddrives

In [54]:
import os
import pandas as pd

folder = "/content/drive/Shareddrives/KCW-Data/kcw_analytics/01_raw"

data = {}

for file in os.listdir(folder):
    if file.endswith(".csv"):
        path = os.path.join(folder, file)
        data[file] = pd.read_csv(
            path,
            dtype={
              "BCODE": "string",
              "ITEMNO": "string",
              "BILLNO": "string",
            },
            encoding="utf-8-sig",
            low_memory=False   # stops chunk guessing
        )
        print(f"Loaded: {file} -> {data[file].shape}")

Loaded: raw_inventory_hq_2024.csv -> (4983, 8)
Loaded: raw_syp_pimas_purchase_bills.csv -> (2975, 49)
Loaded: raw_syp_pidet_purchase_lines.csv -> (27820, 41)
Loaded: raw_syp_simas_sales_bills.csv -> (12941, 49)
Loaded: raw_syp_sidet_sales_lines.csv -> (37967, 38)
Loaded: raw_hq_pimas_purchase_bills.csv -> (50274, 49)
Loaded: raw_hq_pidet_purchase_lines.csv -> (154052, 41)
Loaded: raw_hq_sidet_sales_lines.csv -> (733417, 38)
Loaded: raw_hq_icmas_products.csv -> (114950, 94)
Loaded: raw_hq_armas_receivable.csv -> (2227, 20)
Loaded: raw_hq_apmas_payable.csv -> (978, 20)
Loaded: raw_hq_simas_sales_bills.csv -> (275967, 49)
Loaded: raw_hq_pvmas_notes_vouchers.csv -> (13875, 32)

In [55]:
#"21050289", "22050086", "22050285"
df_hq_pidet = data["raw_hq_pidet_purchase_lines.csv"].copy()

#"21050289", "22010585", "22050259"
df_syp_pidet = data["raw_syp_pidet_purchase_lines.csv"].copy()

In [56]:
df = df_hq_pidet

df["BILLDATE"] = pd.to_datetime(df["BILLDATE"], errors="coerce")

df_hq_21050289 = df[
    df["BCODE"].astype(str).isin(["21050289"]) &
    (df["BILLDATE"].dt.year == 2025)
]

df_hq_22050086 = df[
    df["BCODE"].astype(str).isin(["22050086"]) &
    (df["BILLDATE"].dt.year == 2025)
]

df_hq_22050285 = df[
    df["BCODE"].astype(str).isin(["22050285"]) &
    (df["BILLDATE"].dt.year == 2025)
]

In [57]:
df = df_syp_pidet

df["BILLDATE"] = pd.to_datetime(df["BILLDATE"], errors="coerce")

df_syp_21050289 = df[
    df["BCODE"].astype(str).isin(["21050289"]) &
    (df["BILLDATE"].dt.year == 2025)
]

df_syp_22050259 = df[
    df["BCODE"].astype(str).isin(["22050259"]) &
    (df["BILLDATE"].dt.year == 2025)
]

df_syp_22010585 = df[
    df["BCODE"].astype(str).isin(["22010585"]) &
    (df["BILLDATE"].dt.year == 2025)
]

In [58]:
def format_thai_date(series):
    s = pd.to_datetime(series, errors="coerce")
    return s.dt.strftime("%d/%m/") + (s.dt.year + 543).astype("Int64").astype(str)

In [59]:
def export_dfs_to_excel_same_mapping(dfs_dict, output_file, column_map, date_cols=None):

    date_cols = date_cols or []

    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:
        for sheet_name, df in dfs_dict.items():

            cols = [c for c in column_map if c in df.columns]
            out = df[cols].copy()

            # format Thai date
            for c in date_cols:
                if c in out.columns:
                    s = pd.to_datetime(out[c], errors="coerce")
                    out[c] = s.dt.strftime("%d/%m/") + (s.dt.year + 543).astype("Int64").astype(str)

            out = out.rename(columns=column_map)

            out.to_excel(writer, sheet_name=sheet_name, index=False)

In [60]:
folder = os.path.join(
    BASE_FOLDER,
    "KCW-Data",
    "kcw_analytics",
    "04_outputs",
    "00_temp",
    f"report_2026_03_07.xlsx"
)

# ⭐ create directory if missing
os.makedirs(os.path.dirname(folder), exist_ok=True)

In [61]:
column_map = {
    "BCODE": "รหัสสินค้า",
    "BILLDATE": "วันที่",
    "BILLNO": "เลขที่บิล",
    "PRICE": "่ราคาต่อหน่วย",
    "QTY":"จำนวน",
    "UI":"หน่วย",
    "MTP":"บรรจุ",
    "AMOUNT": "ยอดรวม",
}

dfs_dict = {
    "สำนักงานใหญ่ 22050285": df_hq_22050285,
    "สำนักงานใหญ่ 22050086": df_hq_22050086,
    "สำนักงานใหญ่ 21050289": df_hq_21050289,
    "สี่แยกพัฒนา 22010585": df_syp_22010585,
    "สี่แยกพัฒนา 22050259": df_syp_22050259,
    "สี่แยกพัฒนา 21050289": df_syp_21050289,
}

export_dfs_to_excel_same_mapping(
    dfs_dict=dfs_dict,
    output_file=folder,
    column_map=column_map,
    date_cols=["BILLDATE"]
)

In [81]:
df = df_syp_pidet

df["BILLDATE"] = pd.to_datetime(df["BILLDATE"], errors="coerce")

df_syp_tf = df[
    df["BILLNO"].astype(str).str.contains("TFV", case=False, na=False) &
    (pd.to_datetime(df["BILLDATE"]).dt.year == 2025)
]

In [82]:
df_syp_tf

,ID,JOURMODE,JOURTYPE,JOURDATE,BILLTYPE,BILLDATE,BILLNO,LINE,ITEMNO,BCODE,...,AMOUNT,CHGAMT,ACCTNO,PAID,SALEDATE,SALENO,SALEPRICE,ACCT_NO,CANCELED,DONE
0,15,1,PJ,2025-03-10,1,2025-03-10,TFV6803-001,10,1,03050539,...,463.52,NaN,7KCW,N,NaN,NaN,NaN,7SCL,N,N
1,16,1,PJ,2025-03-10,1,2025-03-10,TFV6803-001,20,2,08056372,...,131.34,NaN,7KCW,N,NaN,NaN,NaN,7SSY1,N,N
11,28,1,PJ,2025-03-18,1,2025-03-18,TFV6803-002,120,12,03052695,...,194.74,NaN,7KCW,N,NaN,NaN,NaN,7GP,N,N
12,29,1,PJ,2025-03-18,1,2025-03-18,TFV6803-002,130,13,23051947,...,177.35,NaN,7KCW,N,NaN,NaN,NaN,7GP,N,N
13,17,1,PJ,2025-03-18,1,2025-03-18,TFV6803-002,10,1,03050145,...,213.78,NaN,7KCW,N,NaN,NaN,NaN,7SCL,N,N
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24245,1448498,1,PJ,2025-12-31,1,2025-12-31,TFV6812-125,20,2,09050665,...,139.40,NaN,7KCW,N,NaN,NaN,NaN,7TYI,N,N
24246,1448499,1,PJ,2025-12-31,1,2025-12-31,TFV6812-125,30,3,02050610,...,650.25,NaN,7KCW,N,NaN,NaN,NaN,7TYI,N,N
24247,1448484,1,PJ,2025-12-31,1,2025-12-31,TFV6812-123,50,5,15010107,...,940.00,NaN,7KCW,N,NaN,NaN,NaN,7VP,N,N
24248,1448485,1,PJ,2025-12-31,1,2025-12-31,TFV6812-123,60,6,15010788,...,699.00,NaN,7KCW,N,NaN,NaN,NaN,7VP,N,N
24249,1448493,1,PJ,2025-12-31,1,2025-12-31,TFV6812-123,140,14,15017070,...,837.00,NaN,7KCW,N,NaN,NaN,NaN,7VP,N,N

In [83]:
df_syp_tf_grouped = (
    df_syp_tf
    .groupby("BILLNO", as_index=False)
    .agg(
        BILLDATE=("BILLDATE", "first"),   # take first date
        line_count=("BILLNO", "size"),    # count rows
        AMOUNT=("AMOUNT", "sum")          # sum amount
    )
)

In [84]:
df_syp_tf_grouped

             BILLNO   BILLDATE  line_count   AMOUNT
0     CNTFV6806-001 2025-06-10           1  -799.72
1     CNTFV6807-001 2025-07-02           1  -804.00
2     CNTFV6808-001 2025-08-28           1 -3200.00
3     CNTFV6809-001 2025-09-10           1 -1786.95
4     CNTFV6809-002 2025-09-10           1 -3573.90
...             ...        ...         ...      ...
1169    TFV6812-123 2025-12-31          14  7952.91
1170    TFV6812-124 2025-12-31           3  3405.62
1171    TFV6812-125 2025-12-31          12  6147.87
1172    TFV6812-126 2025-12-31           2   331.57
1173    TFV6812-127 2025-12-31           2  1390.59

[1174 rows x 4 columns]

In [85]:
import pandas as pd

def export_dfs_to_excel(
    dfs_dict,
    output_file,
    column_map_by_sheet,
    date_cols=None,
):
    """
    dfs_dict:
        {"Sheet1": df1, "Sheet2": df2, ...}

    column_map_by_sheet:
        {
            "Sheet1": {"old_col": "new_col"},
            "Sheet2": {"old_col2": "new_col2"}
        }

    date_cols:
        ["BILLDATE", "VOUCDATE2"]
    """

    date_cols = date_cols or []

    with pd.ExcelWriter(output_file, engine="openpyxl") as writer:

        for sheet_name, df in dfs_dict.items():

            if sheet_name not in column_map_by_sheet:
                raise ValueError(f"No column map defined for sheet {sheet_name}")

            column_map = column_map_by_sheet[sheet_name]

            # keep only mapped columns (and preserve order)
            cols = [c for c in column_map if c in df.columns]
            out = df[cols].copy()

            # Thai date formatting (BE)
            for c in date_cols:
                if c in out.columns:
                    s = pd.to_datetime(out[c], errors="coerce")
                    out[c] = s.dt.strftime("%d/%m/") + (s.dt.year + 543).astype("Int64").astype(str)

            # rename columns
            out = out.rename(columns=column_map)

            out.to_excel(writer, sheet_name=sheet_name, index=False)

In [90]:
dfs_dict = {
    "TFV Bills": df_syp_tf_grouped,
    "TFV Lines": df_syp_tf,
}

In [91]:
column_map_by_sheet = {

    "TFV Bills": {
        "BILLNO": "เลขที่บิล",
        "BILLDATE": "วันที่",
        "line_count": "จำนวนรายการ",
        "AMOUNT": "ยอดรวม",
    },

    "TFV Lines": {
        "BILLDATE": "วันที่",
        "BILLNO": "เลขที่บิล",
        "BCODE": "รหัสสินค้า",
        "PRICE": "่ราคาต่อหน่วย",
        "QTY":"จำนวน",
        "UI":"หน่วย",
        "MTP":"บรรจุ",
        "AMOUNT": "ยอดรวม",
    },
}

In [92]:
folder = os.path.join(
    BASE_FOLDER,
    "KCW-Data",
    "kcw_analytics",
    "04_outputs",
    "00_temp",
    f"tfv_2026_03_07.xlsx"
)

# ⭐ create directory if missing
os.makedirs(os.path.dirname(folder), exist_ok=True)

In [93]:
export_dfs_to_excel(
    dfs_dict,
    folder,
    column_map_by_sheet,
    date_cols=["BILLDATE"]
)

Exception ignored in: <function ZipFile.__del__ at 0x7f685f517ce0>
Traceback (most recent call last):
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1966, in __del__
    self.close()
  File "/usr/lib/python3.12/zipfile/__init__.py", line 1983, in close
    self.fp.seek(self.start_dir)
ValueError: seek of closed file