In [1]:
import os
import sys

if "google.colab" in sys.modules:
    # Running in Colab

    !git clone https://github.com/pthengtr/kcw-analytics.git
    !cd /content/kcw-analytics && git pull origin main

    from google.colab import drive
    drive.mount("/content/drive")

    BASE_FOLDER = "/content/drive/Shareddrives"
    BASE_FOLDER_GIT = "/content"
else:
    # Running in local Jupyter
    BASE_FOLDER = r"G:\Shared drives"
    BASE_FOLDER_GIT = r"C:\Users\Windows 11\Notebook"

print("Using folder:", BASE_FOLDER)

Cloning into 'kcw-analytics'...
remote: Enumerating objects: 720, done.
remote: Counting objects: 100% (79/79), done.
remote: Compressing objects: 100% (62/62), done.
remote: Total 720 (delta 52), reused 30 (delta 17), pack-reused 641 (from 2)
Receiving objects: 100% (720/720), 605.33 KiB | 8.90 MiB/s, done.
Resolving deltas: 100% (485/485), done.
From https://github.com/pthengtr/kcw-analytics
 * branch            main       -> FETCH_HEAD
Already up to date.
Mounted at /content/drive
Using folder: /content/drive/Shareddrives

In [2]:
folder = f"{BASE_FOLDER}/KCW-Data/kcw_analytics/01_raw"

In [3]:
import os
import pandas as pd

data = {}

for file in os.listdir(folder):
    if file.endswith(".csv"):
        path = os.path.join(folder, file)
        data[file] = pd.read_csv(
            path,
            dtype={
              "BCODE": "string",
              "MOBILE": "string",
              "BILLNO": "string",
            },
            encoding="utf-8-sig",
            low_memory=False   # stops chunk guessing
        )
        print(f"Loaded: {file} -> {data[file].shape}")

Loaded: raw_inventory_hq_2024.csv -> (4983, 8)
Loaded: raw_syp_pimas_purchase_bills.csv -> (2996, 49)
Loaded: raw_syp_simas_sales_bills.csv -> (13072, 49)
Loaded: raw_syp_pidet_purchase_lines.csv -> (27958, 41)
Loaded: raw_syp_sidet_sales_lines.csv -> (38241, 38)
Loaded: raw_hq_icmas_products.csv -> (114979, 94)
Loaded: raw_hq_pimas_purchase_bills.csv -> (50325, 49)
Loaded: raw_hq_pidet_purchase_lines.csv -> (154267, 41)
Loaded: raw_hq_sidet_sales_lines.csv -> (733711, 38)
Loaded: raw_hq_armas_receivable.csv -> (2231, 20)
Loaded: raw_hq_apmas_payable.csv -> (978, 20)
Loaded: raw_hq_simas_sales_bills.csv -> (276163, 49)
Loaded: raw_hq_pvmas_notes_vouchers.csv -> (13875, 32)
Loaded: raw_hq_rvmas_notes_vouchers.csv -> (13875, 32)

In [4]:
folder = f"{BASE_FOLDER}/KCW-Data/kcw_analytics/01_raw/online/shopee"

In [9]:
import pandas as pd
import glob
import os

files = glob.glob(os.path.join(folder, "*.xlsx"))

df_shopee_raw = pd.concat(
    (
        pd.read_excel(
            f,
            sheet_name="Income",
            skiprows=5,
            dtype={
              "รหัสสินค้า": "string",     # or the order id column
              "หมายเลขคำสั่งซื้อ": "string"
    }
        )
        for f in files
    ),
    ignore_index=True
)

In [10]:
df_shopee_raw.columns

Index(['ลำดับที่', 'หมายเลขคำสั่งซื้อ', 'รหัสคืนสินค้า',
       'ชื่อผู้ใช้ (ผู้ซื้อ)', 'วันที่ทำการสั่งซื้อ',
       'ช่องทางการชำระเงินของผู้ซื้อ', 'Hot Listing',
       'ช่องทางการชำระเงิน (รายละเอียด)', 'แผนการผ่อนชำระ', 'ค่าธรรมเนียม (%)',
       'วันที่โอนชำระเงินสำเร็จ', 'สินค้าราคาปกติ', 'ส่วนลดสินค้าจากผู้ขาย',
       'จำนวนเงินที่ทำการคืนให้ผู้ซื้อ', 'ส่วนลดสินค้าที่ออกโดย Shopee',
       'โค้ดส่วนลดที่ออกโดยผู้ขาย', 'โค้ดส่วนลดร่วมที่ออกโดยผู้ขาย',
       'Coins Cashback ที่สนับสนุนโดยผู้ขาย',
       'Coins Cashback ร่วมที่สนับสนุนโดยผู้ขาย', 'ค่าจัดส่งที่ชำระโดยผู้ซื้อ',
       'ค่าจัดส่งสินค้าที่ออกโดย Shopee',
       'ค่าจัดส่งที่ Shopee ชำระโดยชื่อของคุณ', 'ค่าจัดส่งสินค้าคืน',
       'ค่าจัดส่งสินค้าคืนผู้ขาย', 'โปรแกรมประหยัดค่าจัดส่งคืนสินค้า',
       'ค่าคอมมิชชั่น AMS', 'ค่าคอมมิชชั่น', 'ค่าบริการ',
       'ค่าธรรมเนียมโครงสร้างพื้นฐานแพลตฟอร์ม',
       'ค่าธรรมเนียม ของโปรแกรมประหยัดค่าจัดส่ง', 'ค่าธุรกรรมการชำระเงิน',
       'ภาษี', 'ค่าธรรมเนียมเติมเงินโฆษณาจากเงิน Escrow',
       'ค่าบริการติดตั้งที่ชำระโดยผู้ซื้อ',
       'ค่าบริการติดตั้งจริงจากผู้ให้บริการ',
       'โบนัสส่วนลดเครื่องเก่าแลกใหม่จากผู้ขาย',
       'จำนวนเงินทั้งหมดที่โอนแล้ว (฿)', 'โค้ดส่วนลด', 'ค่าชดเชยที่หายไป',
       'โปรโมชั่นค่าจัดส่งจากผู้ขาย', 'Shipping provider',
       'ชื่อผู้ให้บริการขนส่ง', 'Unnamed: 42', 'เงินที่คืนไปยังผู้ซื้อ',
       'Shopee Coins ที่ใช้กับสินค้าที่ขอคืน',
       'โค้ดส่วนลด Shopee ที่ใช้กับสินค้าที่ขอคืน',
       'โปรโมชั่นบัตรเครดิตที่ใช้กับสินค้าที่ขอคืน',
       'โปรโมชั่นบัตรเครดิตที่ใช้กับสินค้าที่ขอคืน.1'],
      dtype='object')

In [12]:
df_shopee_raw[['วันที่ทำการสั่งซื้อ','หมายเลขคำสั่งซื้อ', 'รหัสคืนสินค้า', 'สินค้าราคาปกติ','จำนวนเงินทั้งหมดที่โอนแล้ว (฿)']]

,วันที่ทำการสั่งซื้อ,หมายเลขคำสั่งซื้อ,รหัสคืนสินค้า,สินค้าราคาปกติ,จำนวนเงินทั้งหมดที่โอนแล้ว (฿)
0,2026-01-29,260129BBGQVS7P,NaN,540,462
1,2026-01-30,260130CPHQEP8N,NaN,1980,1702
2,2026-01-25,2601250Y0M8BJ9,NaN,3450,2959
3,2026-01-25,2601250AATYBEF,NaN,3500,3000
4,2026-01-27,2601275AY4Q8CS,NaN,3990,3539
...,...,...,...,...,...
98,2026-02-21,260221B0TW90P3,NaN,590,523
99,2026-02-21,260221A59TT49G,NaN,2900,2572
100,2026-02-22,260222CWEM5H8G,NaN,3450,2969
101,2026-02-26,260226PXGABAGU,NaN,6900,5599
102,2026-02-24,260224HXR4W2YV,NaN,370,326

In [18]:
df = df_shopee_raw.copy()

df = df.rename(columns={
    'วันที่ทำการสั่งซื้อ': 'date',
    'หมายเลขคำสั่งซื้อ': 'shopee_no',
    'รหัสคืนสินค้า': 'return',
    'สินค้าราคาปกติ': 'amount_full',
    'จำนวนเงินทั้งหมดที่โอนแล้ว (฿)': 'after_fee'
})

df = df[df["return"].isna()]

df_shopee_cleaned = df[["date", "shopee_no", "amount_full", "after_fee"]]

In [19]:
df_shopee_cleaned

           date       shopee_no  amount_full  after_fee
0    2026-01-29  260129BBGQVS7P          540        462
1    2026-01-30  260130CPHQEP8N         1980       1702
2    2026-01-25  2601250Y0M8BJ9         3450       2959
3    2026-01-25  2601250AATYBEF         3500       3000
4    2026-01-27  2601275AY4Q8CS         3990       3539
..          ...             ...          ...        ...
98   2026-02-21  260221B0TW90P3          590        523
99   2026-02-21  260221A59TT49G         2900       2572
100  2026-02-22  260222CWEM5H8G         3450       2969
101  2026-02-26  260226PXGABAGU         6900       5599
102  2026-02-24  260224HXR4W2YV          370        326

[99 rows x 4 columns]

In [16]:
df_simas = data["raw_hq_simas_sales_bills.csv"].copy()

In [20]:
df_out = df_shopee_cleaned.merge(
    df_simas[["PO", "BILLNO"]],
    how="left",
    left_on="shopee_no",
    right_on="PO"
)

In [22]:
df_out["deduction_pct"] = (
    (df_out["amount_full"] - df_out["after_fee"]) / df_out["amount_full"] * 100
).round(2)

In [23]:
df_out

,date,shopee_no,amount_full,after_fee,PO,BILLNO,deduction_pct
0,2026-01-29,260129BBGQVS7P,540,462,260129BBGQVS7P,TAD6901-621,14.44
1,2026-01-30,260130CPHQEP8N,1980,1702,260130CPHQEP8N,TAD6901-627,14.04
2,2026-01-25,2601250Y0M8BJ9,3450,2959,2601250Y0M8BJ9,TAD6901-526,14.23
3,2026-01-25,2601250AATYBEF,3500,3000,2601250AATYBEF,TAD6901-524,14.29
4,2026-01-27,2601275AY4Q8CS,3990,3539,2601275AY4Q8CS,TAD6901-569,11.30
...,...,...,...,...,...,...,...
94,2026-02-21,260221B0TW90P3,590,523,260221B0TW90P3,TAD6902-484,11.36
95,2026-02-21,260221A59TT49G,2900,2572,260221A59TT49G,TAD6902-482,11.31
96,2026-02-22,260222CWEM5H8G,3450,2969,260222CWEM5H8G,TAD6902-485,13.94
97,2026-02-26,260226PXGABAGU,6900,5599,260226PXGABAGU,TAD6902-582,18.86
98,2026-02-24,260224HXR4W2YV,370,326,260224HXR4W2YV,TAD6902-535,11.89

In [24]:
folder = os.path.join(
    BASE_FOLDER,
    "KCW-Data",
    "kcw_analytics",
    "03_curated",
    f"shopee.csv"
)

# ⭐ create directory if missing
os.makedirs(os.path.dirname(folder), exist_ok=True)

In [25]:
df_out[["BILLNO","deduction_pct"]].to_csv(folder, index=False, encoding="utf-8-sig")